<h1>Usuarios</h1>

<?php $this->mensagem(); ?>

<p>[<a href="<?php echo $this->url(array('action' => 'create')); ?>">novo</a>]</p>

<table border="1">
  <thead>
    <tr>
      <td>Codigo</td>
      <td>Nome</td>
      <td>Email</td>
      <td>Senha</td>
      <td></td>
    </tr>
  </thead>
  <tbody>
      <?php foreach ($this->admin as $admin) { ?>
        <tr>
          <td><?php echo $admin['idadmin'];?></td>
          <td><?php if ($admin['papel'] == '2') { ?>Admin<?php } else { ?>Redator<?php } ?></td>
          <td><?php echo $admin['nome']; ?></td>
          <td><?php echo $admin['email']; ?></td>
          <td><?php echo $admin['senha']; ?></td>
          <td>
            [<a href="<?php echo $this->url(array('action' => 'update', 'idadmin' => $admin['idadmin'])); ?>">editar</a>]
            [<a href="<?php echo $this->url(array('action' => 'delete', 'idadmin' => $admin['idadmin'])); ?>">apagar</a>]
          </td>
        </tr>
    <?php } ?>
  </tbody>
</table>