<h1>Lista dos Pratos</h1>
<?php $this->mensagem(); ?>

<p>[<a href="<?php echo $this->url(array('action' => 'create')); ?>">novo</a>]</p>

<table border="1">
  <thead>
    <tr>
      <td>Codigo</td>
      <td>Descricao do Prato</td>
      <td>Categoria</td>
      <td>Valor</td>
      <td></td>
    </tr>
  </thead>
  <tbody>
      <?php foreach ($this->pratos as $prato){?>
        <tr>
          <td><?php echo $prato['idprato'];?></td>
          <td><?php echo $prato['descricaoprato'];?></td>
          <td><?php echo $prato['categoria'];?></td>
          <td><?php echo $prato['valorprato'];?></td>
          <td>
            <a href="<?php echo $this->url(array('action'=>'update','idprato' => $prato['idprato']));?>">editar</a>
            <?php if($this->podeApagar){?>[<a href="<?php echo $this->url(array('action'=>'delete','idprato'=>$prato['idprato']));?>">apagar</a>]<?php }?>
          </td>
        </tr> <?php }?>
  </tbody>
</table>
